project_id = "lvqvoigbdqhruudmfcou"

[functions.scan-title-pdf]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.setup-telegram-webhook]
verify_jwt = false

[functions.vehicle-data]
verify_jwt = false